DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
 ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
 NAME varchar(256) not null default '', 
 SELLER_NAME varchar(20) not null default '', 
 CATEGORY varchar(256) default '', 
 ASK_PRICE NUMERIC(20, 2) not null default 0, 
 START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
 END_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 STATUS varchar(20),
 PRIMARY KEY(id));
------------------------------------------------------
DROP TABLE IF EXISTS AUCTION;
CREATE TABLE AUCTION ( 
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    PRODUCT_ID INT NOT NULL default 0,  
    END_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    STATUS VARCHAR(20), 
    BID_PRICE DECIMAL(10,2) not null default 0, 
    BUYER_ID VARCHAR(20) ,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID));
------------------------------------------------------
DROP TABLE IF EXISTS BID;
CREATE TABLE BID ( 
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    PRODUCT_ID INT  NOT NULL, 
    BUYER_ID VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20), 
    BIDDING_PRICE DECIMAL(10,2),  
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID));
------------------------------------------------------
